local devs = {
  dekyoDev = {
    Display = dekyo,
    User = dekyoDev,
    Role = coder, designer,
    UrlPfp = "https://raw.githubusercontent.com/HS1HYDRAX7/45786153617475726E/refs/heads/main/assets/dekyo_pfp.png",
    UrlBanner = "https://raw.githubusercontent.com/HS1HYDRAX7/45786153617475726E/refs/heads/main/assets/dekyo_banner.png"
  },
  
  atlasDev = {
    Display = Atlas,
    User = Atlas_coder,
    Role = coder,
    UrlPfp = "https://raw.githubusercontent.com/HS1HYDRAX7/45786153617475726E/refs/heads/main/assets/atlas_pfp.png",
    UrlBanner = "https://raw.githubusercontent.com/HS1HYDRAX7/45786153617475726E/refs/heads/main/assets/atlas_banner.png"
  }
}

local banners = {}
